services:
  # MySQL Service
  mysql-contact-form:
    image: mysql:latest
    container_name: mysql-contact-form
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${HOST_MYSQL_PORT}:${CONT_MYSQL_PORT}"
    volumes:
      - mysql-contact-form-data:/var/lib/mysql
    networks:
      - contact-form-network-database

  # API Contact Form Service
  api-contact-form:
    build: .
    image: api-contact-form:1.0.0
    container_name: api-contact-form
    restart: on-failure
    depends_on:
      - mysql-contact-form
    env_file:
      - .env
    ports:
      - "${HOST_API_PORT}:${CONT_API_PORT}"
    environment:
      - APP_PORT=${CONT_API_PORT}
      - APP_TIMEZONE=Asia/Jakarta
      - DB_HOST=mysql-contact-form
      - DB_PORT=${CONT_MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - CORS_ALLOWED_ORIGINS=http://localhost:8081,http://localhost:8082,http://cms-contact-form:8081,http://client-contact-form:8082
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Origin,Content-Type,Accept,Authorization
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_EXPOSE_HEADERS=Content-Length,Content-Type
    networks:
      - contact-form-network-database


volumes:
  mysql-contact-form-data:

networks:
  contact-form-network-database:
    driver: bridge